### PR TITLE
fix : #96 Add support for both DECLARAI_OPEN_AI_KEY and OPENAI_API_KEY

### LINKED ISSUE #96: Support `OPENAI_API_KEY` env var
Most libraries and services that have to do with OpenAI, and need an api token, support the `OPENAI_API_KEY` env var. So I often export `OPENAI_API_KEY` to my shell session once, and that satisfies the requirements of most tools.

But Declarai specially requires `DECLARAI_OPENAI_API_KEY`, which introduces some friction to my workflow. 

image

Please support `OPENAI_API_KEY`. You can still support `DECLARAI_OPENAI_API_KEY` and even give precedence to it over `OPENAI_API_KEY` if both exist.

Thanks!

### PR DESCRIPTION
**Pull request by shobhit9957**
## Description

This pull request addresses issue #96 . It adds support for both `DECLARAI_OPEN_AI_KEY` and `OPENAI_API_KEY` environment variables in the `settings.py` file. This change ensures compatibility with existing workflows that utilize the `OPENAI_API_KEY` environment variable.

## Changes Made

- Modified the `settings.py` file to support both `DECLARAI_OPEN_AI_KEY` and `OPENAI_API_KEY`.
- Updated the code to check for the presence of either environment variable and use the appropriate value.

## Testing Done

- Tested the changes locally by setting different combinations of `DECLARAI_OPEN_AI_KEY` and `OPENAI_API_KEY` environment variables.
- Ran existing test suite to ensure that the changes did not introduce any regressions.

## Impact

This change improves the user experience by allowing users to utilize the more common `OPENAI_API_KEY` environment variable, while still providing support for the project-specific `DECLARAI_OPEN_AI_KEY`.

## Related Issues

Closes #96

### CODE REVIEW

**Comment by matankley** [comment]
Hey! it looks great! 
One small thing, The CI fails on pre-commit step because of formatting the `settings.py`
Can you please run `pre-commit --all-files` on your env and push the changes ? 

Thanks!
Once the CI succeeded we can merge it 💯

**Comment by shobhit9957** [comment]
hey, it's done 😊

**Review by matankley — APPROVED** [review]

**Comment by matankley** [comment]
@shobhit9957 Thanks for your contribution, we appreciate it !
I'm planning to publish a new release next week, and this will be part of it of course.

**Comment by shobhit9957** [comment]
Hey thanks @matankley . I enjoyed it a lot.😊

**Pull request merged**
