### PR TITLE
Closes #63 add deployment example with fastapi for declarai task

### LINKED ISSUE #63: Add deployment example with fastapi for declarai task

### PR DESCRIPTION
**Pull request by matankley**

### CODE REVIEW

**Comment by avivex1000** [comment]
How do you feel about putting this in an "examples/deployments" tab instead of just deployments?
Also, maybe this or a separate example leveraging dependency injection?

**Comment by matankley** [comment]
Currently when used with Depends the swagger shows kwargs as input params rather then user_input (for the movie recommendation example).
image
image

**Comment by matankley** [comment]
And defenitely, moved it to examples/deployments
image

**Comment by avivex1000** [comment]
> Currently when used with Depends the swagger shows kwargs as input params rather then user_input (for the movie recommendation example).
> 
> image
> 
> image
> 
> 

I see, We might need to extend the decorator to override the LLMTaskOrchestrator __call__ method with the type hints for this to work because Im pretty sure swagger is evaluated in runtime so this should cause it to appear in the swagger as well.
Not urgent but maybe a separate issue, not sure what other implications this might have (like other tools relying on runtime type hints 🙂)

**Review by avivex1000 — APPROVED** [review]
Also another thought, I see many apps supporting streaming, might be worth considering at some point as well although except for it looking cool, I'm not sure the concrete value for "smallish" payloads yet

**Pull request merged**
