### PR TITLE
Support pydantic Field description

### PR DESCRIPTION
**Pull request by helmanofer**
This not a simple bugfix
WDYT?

### CODE REVIEW

**Comment by matankley** [comment]
@helmanofer Wow that's an amazing idea!. I'll take a deep look later on today.
We should definitely integrate this feature.

**Comment by matankley** [comment]
The descriptions are compiled beautifully within the prompt :)
Regarding the unions (multi type) it works great on Unions of primitives, but as far as i understand array or objects are compiled into the prompt as array / object without addressing the nuances of List[str] and List[int]. 

For example I tested the compilation of:
`    ids: Union[List[str], List[int]] = Field(description="A list of two identifiers")
`

Results in - 
`ids': 'array or array - A list of two identifiers'` instead of for example `ids: 'array of string or array of int'...`

Despite that, I think the better place for the 'or' manipulation  ` obj_type = ' or '.join(obj_types_list)`, is under `type_annotation_to_str_schema` function, which is the one actually returning a str value.

I would return the description and additional information within the schema , and then manipulate it under `type_annotation_to_str_schema`.

WDYTH ?

**Comment by avivex1000** [comment]
@helmanofer @matankley 
Do `Union` and `|` behave the same way here? 
As we are intentionally not using the `|` syntax in order to support older versions of python, `Union` must behave properly here, that being said, it would be awesome if the pipe syntax works just the same 😇.

I would also add a test for these separate scenarios specifically given the change in the resulting string prompt.

If this doesn't break the existing behavior, I'm pro adding this and dealing with the support for complex types later @matankley. If I recall correctly we might have another place with a similar issue 🤔

**Comment by helmanofer** [comment]
@matankley @avivex1000 thanks for your comments. I will have a thorough read of your comments this weekend and update my code accordingly. In any case you are more than welcome to continue the work yourself

**Comment by helmanofer** [comment]
Hi, 

Adding the multi-type isn't trivial
Some approaches that I tried weren't handled well either by pydantic or by ChatGPT.
I opened a different PR for the description (I messed up a little)

**Pull request closed without merging**
